name: "Collect data"
description: "Collect data for fetch purpose"
inputs:
  # basic data
  owner:
    description: "owner of the repository"
    required: true
    default: "codinasion"

  # token for github api authentication (auto generation)
  token:
    description: "github personal access token"
    required: true

  # personal token for github api authentication
  PAT:
    description: "github personal access token"
    required: false

  # programme repo related data
  programme-repo:
    description: "programme repository name"
    required: true
    default: "codinasion-programme"

  programme-branch:
    description: "programme repository branch"
    required: true
    default: "master"

  # dsa repo related data
  dsa-repo:
    description: "dsa repository name"
    required: true
    default: "codinasion-dsa"

  dsa-branch:
    description: "dsa repository branch"
    required: true
    default: "master"

  # quote repo related data
  quote-repo:
    description: "quote repository name"
    required: true
    default: "readme-quote"

  quote-branch:
    description: "quote repository branch"
    required: true
    default: "master"

  # function trigger conditions
  collect-programme:
    description: "collect programme data"
    required: true
    default: "false"

  process-programme:
    description: "process programme data"
    required: true
    default: "false"

  collect-dsa:
    description: "collect dsa data"
    required: true
    default: "false"

  process-dsa:
    description: "process dsa data"
    required: true
    default: "false"

  collect-quote:
    description: "collect quote data"
    required: true
    default: "false"

  process-quote:
    description: "process quote data"
    required: true
    default: "false"

  collect-tag:
    description: "collect tag data"
    required: true
    default: "false"

  process-tag:
    description: "process tag data"
    required: true
    default: "false"

  collect-stats:
    description: "collect stats data"
    required: true
    default: "false"

runs:
  using: "node16"
  main: "../dist/index.js"
