name: "Collect data"
description: "Collect data for fetch purpose"
inputs:
  # basic data
  owner:
    description: "owner of the repository"
    required: true
    default: "codinasion"

  # token for github api authentication (auto generation)
  token:
    description: "github personal access token"
    required: true

  # personal token for github api authentication
  PAT:
    description: "github personal access token"
    required: false

  # home data related data
  project-topic:
    description: "topic keyword to collect project data"
    required: true
    default: "codinasion-project"

  # programme repo related data
  programme-repo:
    description: "programme repository name"
    required: true
    default: "codinasion-programme"

  programme-branch:
    description: "programme repository branch"
    required: true
    default: "master"

  # dsa repo related data
  dsa-repo:
    description: "dsa repository name"
    required: true
    default: "codinasion-dsa"

  dsa-branch:
    description: "dsa repository branch"
    required: true
    default: "master"

  # blog repo related data
  blog-repo:
    description: "blog repository name"
    required: true
    default: "codinasion-blog"

  blog-branch:
    description: "blog repository branch"
    required: true
    default: "master"

  # function trigger conditions
  collect-project:
    description: "collect project data"
    required: true
    default: "false"

  collect-programme:
    description: "collect programme data"
    required: true
    default: "false"

  process-programme:
    description: "process programme data"
    required: true
    default: "false"

  collect-dsa:
    description: "collect dsa data"
    required: true
    default: "false"

  process-dsa:
    description: "process dsa data"
    required: true
    default: "false"

  collect-blog:
    description: "collect blog data"
    required: true
    default: "false"

  process-blog:
    description: "process blog data"
    required: true
    default: "false"

  collect-programme-tag:
    description: "collect programme tag data"
    required: true
    default: "false"

  process-programme-tag:
    description: "process programme tag data"
    required: true
    default: "false"

  collect-blog-tag:
    description: "collect blog tag data"
    required: true
    default: "false"

  process-blog-tag:
    description: "process blog tag data"
    required: true
    default: "false"

  collect-stats:
    description: "collect stats data"
    required: true
    default: "false"

  generate-humans:
    description: "generate humans.txt"
    required: true
    default: "false"

runs:
  using: "node16"
  main: "../dist/index.js"
