name: Collect Programme Data

# triger conditions
on:
  # manually triggered
  workflow_dispatch:
  # runs every two hour
  schedule:
    - cron: "0 0/6 * * *"
  # on push to master
  push:
    branches: [master]

jobs:
  collect_data:
    runs-on: ubuntu-latest
    name: Collect Programme Data

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ##########  Get Date  ##########
      - name: Get Date
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 5.5
          format: "YYYY-MM-DD-hh-mm"

      ##########  Install packages  ##########
      - name: Yarn
        run: |
          yarn

      - name: Commit Script Files
        uses: EndBug/add-and-commit@v9
        with:
          message: "update script - ${{ steps.date.outputs.time }}"

      ##########  Update Script  ##########
      - name: Update Script
        run: |
          cd scripts
          wget 'https://raw.githubusercontent.com/codinasion/codinasion/master/script/formatTag.js' -O formatTag.js

      - name: Commit Script Files
        uses: EndBug/add-and-commit@v9
        with:
          message: "update script - ${{ steps.date.outputs.time }}"

      ##########  collect programme data  ##########
      - name: Collect Programme Data
        uses: ./action/
        with:
          collect-programme: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Programme Data
        uses: EndBug/add-and-commit@v9
        with:
          message: "programme list data - ${{ steps.date.outputs.time }}"

      ##########  process programme data  ##########
      - name: Process Programme Data
        uses: ./action/
        with:
          process-programme: true
          token: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.API_DATA_FETCH_PAT }}

      - name: Commit Processed Programme Data
        uses: EndBug/add-and-commit@v9
        with:
          message: "programme data - ${{ steps.date.outputs.time }}"
