name: Collect DSA Data

# triger conditions
on:
  # manually triggered
  workflow_dispatch:
  # runs after programme.yml
  workflow_run:
    workflows: ["Collect Programme Data"]
    types:
      - completed

jobs:
  collect_data:
    runs-on: ubuntu-latest
    name: Collect DSA Data

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ##########  Get Date  ##########
      - name: Get Date
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 5.5
          format: "YYYY-MM-DD-hh-mm"

      ##########  collect dsa data  ##########
      - name: Collect DSA Data
        uses: ./action/
        with:
          collect-dsa: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit DSA Data
        uses: EndBug/add-and-commit@v9
        with:
          message: "dsa list data - ${{ steps.date.outputs.time }}"

      ##########  process dsa data  ##########
      - name: Process DSA Data
        uses: ./action/
        with:
          process-dsa: true
          token: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.API_DATA_FETCH_PAT }}

      - name: Commit Processed DSA Data
        uses: EndBug/add-and-commit@v9
        with:
          message: "dsa data - ${{ steps.date.outputs.time }}"
