name: Collect Stats Data

# triger conditions
on:
  # manually triggered
  workflow_dispatch:
  # runs after programme-tag.yml
  workflow_run:
    workflows: ["Collect Programme Tag Data"]
    types:
      - completed

jobs:
  collect_data:
    runs-on: ubuntu-latest
    name: Collect Stats Data

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ##########  Get Date  ##########
      - name: Get Date
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 5.5
          format: "YYYY-MM-DD-hh-mm"

      ##########  collect stats data  ##########
      - name: Collect Stats Data
        uses: ./action/
        with:
          collect-stats: true
          token: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.API_DATA_FETCH_PAT }}

      - name: Commit Stats Data
        uses: EndBug/add-and-commit@v9
        with:
          message: "data - ${{ steps.date.outputs.time }}"
