name: Collect Blog Data

# triger conditions
on:
  # manually triggered
  workflow_dispatch:
  # runs everyday at 00:00 IST or 18:30 UTC and every 12 hours after that
  schedule:
    - cron: "30 18/12 * * *"
  # on push to master
  push:
    branches: [master]

jobs:
  collect_data:
    runs-on: ubuntu-latest
    name: Collect Blog Data

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ##########  Get Date  ##########
      - name: Get Date
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 5.5
          format: "YYYY-MM-DD-hh-mm"

      ##########  collect blog data  ##########
      - name: Collect Blog Data
        uses: ./action/
        with:
          collect-blog: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Blog Data
        uses: EndBug/add-and-commit@v9
        with:
          message: "blog list data - ${{ steps.date.outputs.time }}"

      # ##########  process Blog data  ##########
      # - name: Process Blog Data
      #   uses: ./action/
      #   with:
      #     process-blog: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     PAT: ${{ secrets.API_DATA_FETCH_PAT }}

      # - name: Commit Processed Blog Data
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     message: "blog data - ${{ steps.date.outputs.time }}"
